/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VennDiagramFX;
//Commit
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
