/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package VennDiagramFX;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}

/*User Manual's
Common Usage 
Scenarios

If a user completed 
a survey consisting 
of 8 people on which 
sport, they would 
rather play, Soccer 
or Basketball or no 
preference. The user 
may want to create 
a simple Venn diagram 
to display the names 
of the individuals who 
chose Soccer or 
Basketball and those 
who do not have a 
preference between 
the two. 

After launching the 
Venn diagram 
application, the user 
may change the title 
located at the top of 
the Venn diagram to 
‘Soccer v Basketball’. 
In order to do this 
the user will have to 
click the ‘Insert Title’ 
located on the top of 
the Venn Diagram and 
type 
‘Soccer v Basketball’. 

Now the user may want 
to add sub-titles 
(Soccer on the Left 
and Basketball on 
the right), and in 
order to do this, 
the user will have to 
click the ‘Insert Title’ 
located inside of 
the left circle and 
type ‘Soccer’, and then 
user will click the 
‘Insert Title’ located 
inside of the right 
circle and type 
‘Basketball’.

After doing all that, 
the user will enter the 
names of all the 
individuals that 
participated in the 
survey. In order to do 
this the user can 
double click anywhere 
inside or outside of 
the Venn diagram a label 
will appear that looks 
like this:

Insert text 1

Now the user can edit 
the text. A tab of 
the left named home 
allows the user to 
edit the text 
properties (Size, 
Font, Text Style, 
Text Colour) and the 
text itself. The user 
can then edit the Text 
at the bottom and enter 
the desired text. In 
this case, say the 
user wants size 14 font 
that is italics. In 
order to do this the 
user will select the 
text they want to 
change, and the home 
tab on the left will 
pop up, from there the 
user can change the size 
property to 14.0 under 
the ‘Size; tab, select 
Italics under the 
‘Text Style’ section, 
and under the ‘Text’ 
section the user can 
enter:

Alex Orlando

The user can then 
enter the names of 
the rest of the 
people that 
participated in the 
survey in the same 
way the user did 
with the first name. 
In this case the 
user will enter:

Blake White 

Chloe James

Jose Rodrigo

Harman Dhillon

Martha Silver

Jessica Grewal

Ken Lee

If the user entered 
all the names on 
one side or if they 
are not located 
where the user 
wants them to be, 
then the user can 
drag the names to 
their desired 
location. In this 
case, let’s say the 
first three names 
are for Soccer, the 
next three names 
are for basketball, 
and the last two 
are for those who 
do not have a 
preference between 
the two. 
So, 

Alex Orlando, 
Blake White 
and 
Chloe James 

will be on the left 
side of the Venn 
diagram under 
‘Soccer’. The right 
side of the Venn 
diagram under 
‘Basketball’ will 
have the names 

Jose Rodrigo, 
Harman Dhillon, 
and 
Jessica Grewal. 

In the middle of 
the Venn diagram 
where the two 
circles intersect, 
there will be two 
names that are 

Martha Silver 
and 
Ken Lee.

Since the user 
has wrote all 
the names down 
and drag the 
text into their 
desired placement, 
they can deselect 
‘Click to add 
Text’ and 
‘Drag Text’ 
located at the 
bottom of the 
program.

If the user does 
not like the 
colour of the 
Venn diagram or 
wants to change 
the size of the 
Venn diagram, then 
the user can click 
the design tab and 
change the size of 
either or both 
circles and the 
colour of either 
of both circles. 
In this case, 
say the user 
wants a custom 
green circle for 
the left circle 
‘Soccer’ and a 
default orange for 
the right circle 
‘Basketball’. Also, 
the user may want 
to change the size 
of both circles of 
the Venn diagram 
from the default 
250 to 240.

In order to change 
the colour of the 
left circle ‘Soccer’ 
to a custom green 
(#OOff00), the user 
has to click the 
design section on 
the left, select 
‘Left Circle’ and 
under the ‘Colour’ 
section the user can 
click the drop down 
menu, and select 
‘Custom Colour …’ 
at the bottom. Then 
the user can slide 
the colour tool bar 
to the middle of 
the green section 
and drag the small circle in the square on the left all the way to the top right to get the right custom colour. If the user wants to use this colour again in the future, they can click the ‘Save’ button on the bottom right or they can click the ‘Use’ button if they only want to use it this one time. 
Now to change the right circle’s colour to Blue (#334db3), the user will select ‘Right Circle’ under the design tab. Then click the drop-down menu under ‘Colour’ and select the default blue colour in the fourth row and second column. The colours should be changed of both circles now. 
To change the size of the entire Venn diagram, select ‘Both Circles’ under the design tab. And the user can either use the toolbar to drag the circle to 240 or manually change the size to 240 by editing the small box beside the ‘Size’ section. 

*/